version: "3.8"
services:
  client:
    image: maciekek/my-pi-home-client:latest

    #    build:
#      context: ./client
#      dockerfile: Dockerfile-dev
#    command: sh -c "./start-dev.sh"
#    command: sh -c "ls"
#    volumes:
#      - ./client/:/user/src/app
#    environment:
#      - REACT_APP_API_URL=http://77.55.217.143:8888
    ports:
      - "3000:3000"
    networks:
      - app

volumes:
   mongodb:

networks:
  db:
  app:

